services:
  qreye:
    build: .
    container_name: qreye_c
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "80:80"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true
    tty: true
